site_name: 山西农业大学开源软件团队
theme:
  language: zh
  name: material
  logo: assets/129314812.jpg
  favicon: assets/129314812.jpg
  palette:
      primary: pink
  features:
    - navigation.instant
    - navigation.tracking
extra:
  homepage: #
  constent:
    title: Cookie政策
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.