site_name: 山西农业大学开源软件团队
site_url: https://meowrain.github.io/doc-for-sxau/
site_description: >-
  山西农业大学开源软件团队文档
repo_name: doc-for-sxau
repo_url: https://github.com/meowrain/doc-for-sxau
copyright: Copyright &copy; 2023-present <a href="https://github.com/meowrain" target="_blank" rel="noopener noreferrer">MeowRain</a>
theme:
  language: zh
  name: material
  logo: assets/129314812.jpg
  favicon: assets/129314812.jpg
  palette:
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: 切换到黑暗模式
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-3
          name: 切换到白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
extra:
  homepage: #
  constent:
    title: Cookie政策
    description: 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
